### PR TITLE
Added "api" node for free form API

### PR DESCRIPTION
**Pull request by ybizeul**
See #1

### CODE REVIEW

**Comment by KevinBonnoron** [comment]
Hello !

I understand what you need, and i think we should implement it, but thoses changes would break the 2 existings nodes (and i am using both of them actually :)).
Maybe you should not extend BaseNode, for this kind of needs, but reimplement it's code in the new ApiNode.

**Comment by ybizeul** [comment]
Good, that's actually what I did :-) Not super clean, but it works in a new API node

**Comment by KevinBonnoron** [comment]
You didn't reimplement the code from BaseNode.
I just commited a new version with the changes you requested.

Thanks for your contribution

**Comment by ybizeul** [comment]
Ha I see, I thought you meant my code should inherit BaseNode, which is what I did, you took the code from BaseNode to create a new class, I see.

Thanks for the quick work !!

**Pull request closed without merging**
